services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: necro-wiki-client
    ports:
      - "6019:80"
    restart: always
    networks:
      - necro_network

networks:
  necro_network:
    external: true